Repository UBC-MDS/DSCI-532-2025-02-vanparks_finder, pull requests merged in 2025-03, with the labels that each got.

#37 Deployment
  src/app.py
Labels: enhancement

#54 Create bar_chart.py
  src/app.py
  src/assets/__init__.py
  src/callbacks/__init__.py
  src/callbacks/bar_chart.py
  src/components/__init__.py
  src/components/bar_chart.py
  src/data/__init__.py
  src/data/data.py
Labels: enhancement

#56 moving map out of app.py
  src/app.py
  src/callbacks/__init__.py
  src/callbacks/map.py
  src/components/__init__.py
  src/components/map.py
  src/data/data.py
Labels: enhancement

#58 Hover, reformat
  src/app.py
  src/callbacks/__init__.py
  src/callbacks/modal.py
  src/components/__init__.py
  src/components/cards.py
  src/components/filter.py
  src/components/map.py
  src/components/modal.py
Labels: enhancement

#60 fix deployment error
  src/app.py
  src/callbacks/bar_chart.py
  src/callbacks/map.py
  src/callbacks/modal.py
  src/components/bar_chart.py
  src/components/filter.py
  src/components/map.py
Labels: bug

#61 Map boundaries
  data/raw/neighbourhood-boundary.geojson
  src/callbacks/map.py
  src/components/filter.py
  src/components/map.py
  src/data/__init__.py
  src/data/data.py
Labels: enhancement

#62 Reflection
  reports/m3-reflection.md
  src/app.py
Labels: enhancement

#63 changing readme
  README.md
  src/__init__.py
  src/app.py
Labels: documentation

#76 Address feedback
  .gitignore
  CONTRIBUTING.md
  README.md
  data/processed/parks-facilities.parquet
  data/processed/parks-special-features.parquet
  data/processed/parks.parquet
  data/raw/neighbourhood-boundary.geojson
  data/raw/parks-facilities.parquet
  data/raw/parks-special-features.parquet
  data/raw/parks.parquet
  environment.yml
  requirements.txt
  src/callbacks/map.py
  src/data/data.py
  src/data/download_data.py
Labels: documentation

#80 changed bar chart title and axis labels
  src/components/bar_chart.py
Labels: enhancement
