Repository UBC-MDS/DSCI-532-2025-02-vanparks_finder, pull requests merged in 2025-02, with the labels that each got.

#1 Repo structure
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  data/raw/parks-facilities.csv
  data/raw/parks-special-features.csv
  data/raw/parks.csv
  environment.yml
  reports/m1_proposal.md
  src/app.py
Labels: enhancement

#6 Docs m1
  LICENSE
  LICENSE.md
  README.md
Labels: documentation

#7 Finalize m1
  img/sketch.png
  reports/m1_proposal.md
Labels: documentation

#30 Left filter m2
  app.py
  src/app.py
Labels: enhancement

#32 bug fix for facilties and special features
  src/app.py
Labels: bug

#34 Bar chart
  src/app.py
Labels: enhancement

#35 Deployment
  requirements.txt
  src/app.py
Labels: enhancement
